// scripts/vue/Card.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  [
    'rounded-xl border border-[var(--color-border)] bg-[var(--color-surface-1)]',
    'text-[var(--color-text-1)]',
    'transition-colors duration-150',
    props.class,
  ]
    .filter(Boolean)
    .join(' ')
)
</script>

<template>
  <div :class="classes" data-slot="card">
    <slot />
  </div>
</template>

// scripts/svelte/card.svelte
<script lang="ts">
  import type { Snippet } from "svelte"

  interface Props {
    class?: string
    children?: Snippet
    [key: string]: unknown
  }

  let { class: className, children, ...rest }: Props = $props()
</script>

<div
  class="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface-1)] text-[var(--color-text-1)] shadow-sm transition-colors {className ?? ''}"
  {...rest}
>
  {@render children?.()}
</div>
