// scripts/vue/Separator.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(
  defineProps<{
    orientation?: 'horizontal' | 'vertical'
    class?: string
  }>(),
  { orientation: 'horizontal' }
)

const classes = computed(() =>
  [
    'shrink-0 bg-[var(--color-border)]',
    props.orientation === 'horizontal' ? 'h-px w-full' : 'h-full w-px',
    props.class,
  ]
    .filter(Boolean)
    .join(' ')
)
</script>

<template>
  <div
    role="separator"
    :aria-orientation="orientation"
    :class="classes"
  />
</template>

// scripts/svelte/separator.svelte
<script lang="ts">
  interface Props {
    orientation?: "horizontal" | "vertical"
    class?: string
    [key: string]: unknown
  }

  let { orientation = "horizontal", class: className, ...rest }: Props = $props()

  const isHorizontal = $derived(orientation === "horizontal")
</script>

{#if isHorizontal}
  <div
    role="separator"
    aria-orientation="horizontal"
    class="h-px w-full bg-[var(--color-border)] shrink-0 {className ?? ''}"
    {...rest}
  ></div>
{:else}
  <div
    role="separator"
    aria-orientation="vertical"
    class="w-px h-full bg-[var(--color-border)] shrink-0 {className ?? ''}"
    {...rest}
  ></div>
{/if}
