// scripts/vue/Avatar.vue
<script setup lang="ts">
import { computed, ref } from 'vue'

const props = withDefaults(
  defineProps<{
    src?: string
    alt?: string
    fallback?: string
    size?: 'sm' | 'md' | 'lg'
    class?: string
  }>(),
  { size: 'md', alt: '' }
)

const imgError = ref(false)

const sizeClasses: Record<string, string> = {
  sm: 'h-7 w-7 text-xs',
  md: 'h-9 w-9 text-xs',
  lg: 'h-12 w-12 text-sm',
}

const containerClasses = computed(() =>
  [
    'relative flex shrink-0 overflow-hidden rounded-full',
    sizeClasses[props.size],
    props.class,
  ]
    .filter(Boolean)
    .join(' ')
)

const showImage = computed(() => !!props.src && !imgError.value)

function onError() {
  imgError.value = true
}
</script>

<template>
  <div :class="containerClasses">
    <img
      v-if="showImage"
      :src="src"
      :alt="alt"
      class="aspect-square h-full w-full object-cover"
      @error="onError"
    />
    <div
      v-else
      class="flex h-full w-full items-center justify-center rounded-full bg-[var(--color-surface-2)] text-[var(--color-text-2)] font-medium"
    >
      {{ fallback }}
    </div>
  </div>
</template>

// scripts/components/avatar.tsx
"use client"

import * as React from "react"
import * as AvatarPrimitive from "@radix-ui/react-avatar"

const Avatar = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Root> & {
    ring?: boolean
  }
>(({ className, ring = false, ...props }, ref) => (
  <AvatarPrimitive.Root
    ref={ref}
    className={[
      "relative flex h-9 w-9 shrink-0 overflow-hidden rounded-full",
      ring && "ring-2 ring-[var(--color-accent)] ring-offset-2 ring-offset-[var(--color-bg)]",
      className,
    ]
      .filter(Boolean)
      .join(" ")}
    {...props}
  />
))
Avatar.displayName = AvatarPrimitive.Root.displayName

const AvatarImage = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Image>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Image>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Image
    ref={ref}
    className={["aspect-square h-full w-full object-cover", className].filter(Boolean).join(" ")}
    {...props}
  />
))
AvatarImage.displayName = AvatarPrimitive.Image.displayName

const AvatarFallback = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Fallback>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Fallback>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Fallback
    ref={ref}
    className={[
      "flex h-full w-full items-center justify-center rounded-full",
      "bg-[var(--color-surface-2)] text-[var(--color-text-2)] text-xs font-medium",
      className,
    ]
      .filter(Boolean)
      .join(" ")}
    {...props}
  />
))
AvatarFallback.displayName = AvatarPrimitive.Fallback.displayName

export { Avatar, AvatarImage, AvatarFallback }
