// scripts/svelte/card-title.svelte
<script lang="ts">
  import type { Snippet } from "svelte"

  interface Props {
    class?: string
    children?: Snippet
    [key: string]: unknown
  }

  let { class: className, children, ...rest }: Props = $props()
</script>

<h3
  class="text-lg font-semibold leading-none tracking-tight text-[var(--color-text-1)] {className ?? ''}"
  {...rest}
>
  {@render children?.()}
</h3>

// scripts/vue/CardTitle.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  [
    'text-base font-semibold leading-tight tracking-tight text-[var(--color-text-1)]',
    props.class,
  ]
    .filter(Boolean)
    .join(' ')
)
</script>

<template>
  <div :class="classes" data-slot="card-title">
    <slot />
  </div>
</template>
