// scripts/components/separator.tsx
"use client"

import * as React from "react"
import * as SeparatorPrimitive from "@radix-ui/react-separator"

const Separator = React.forwardRef<
  React.ElementRef<typeof SeparatorPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof SeparatorPrimitive.Root>
>(({ className, orientation = "horizontal", decorative = true, ...props }, ref) => (
  <SeparatorPrimitive.Root
    ref={ref}
    decorative={decorative}
    orientation={orientation}
    className={[
      "shrink-0 bg-[var(--color-border)]",
      orientation === "horizontal" ? "h-px w-full" : "h-full w-px",
      className,
    ]
      .filter(Boolean)
      .join(" ")}
    {...props}
  />
))
Separator.displayName = SeparatorPrimitive.Root.displayName

export { Separator }

// scripts/vue/Separator.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = withDefaults(
  defineProps<{
    orientation?: 'horizontal' | 'vertical'
    class?: string
  }>(),
  { orientation: 'horizontal' }
)

const classes = computed(() =>
  [
    'shrink-0 bg-[var(--color-border)]',
    props.orientation === 'horizontal' ? 'h-px w-full' : 'h-full w-px',
    props.class,
  ]
    .filter(Boolean)
    .join(' ')
)
</script>

<template>
  <div
    role="separator"
    :aria-orientation="orientation"
    :class="classes"
  />
</template>
