// apps/web/src/components/ui/skeleton.tsx
import * as React from "react"

function Skeleton({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      data-slot="skeleton"
      className={[
        "animate-pulse rounded-md",
        "bg-[var(--color-surface-2)]",
        className,
      ]
        .filter(Boolean)
        .join(" ")}
      {...props}
    />
  )
}

export { Skeleton }

// scripts/vue/Skeleton.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  ['animate-pulse rounded-md bg-[var(--color-surface-2)]', props.class]
    .filter(Boolean)
    .join(' ')
)
</script>

<template>
  <div :class="classes" data-slot="skeleton" />
</template>
