// scripts/svelte/tabs-list.svelte
<script lang="ts">
  import type { Snippet } from "svelte"

  interface Props {
    class?: string
    children?: Snippet
    [key: string]: unknown
  }

  let { class: className, children, ...rest }: Props = $props()
</script>

<div
  role="tablist"
  class="inline-flex h-9 items-center justify-center rounded-lg bg-[var(--color-surface-2)] p-1 text-[var(--color-text-3)] {className ?? ''}"
  {...rest}
>
  {@render children?.()}
</div>

// scripts/vue/TabsList.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  class?: string
}>()

const classes = computed(() =>
  [
    'inline-flex h-9 items-center justify-center rounded-lg p-1',
    'bg-[var(--color-surface-1)] border border-[var(--color-border)]',
    'text-[var(--color-text-3)]',
    props.class,
  ]
    .filter(Boolean)
    .join(' ')
)
</script>

<template>
  <div role="tablist" :class="classes">
    <slot />
  </div>
</template>
